// buildbrand_react_new/buildbrand_react/src/components/FeatureCards/FeatureCards.tsx
import { useEffect, useRef } from 'react'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger'
import './FeatureCards.scss'

const features = [
    {
        number: "01",
        title: "Brand Clarity",
        description: "Clarity of the brand's purpose, audience, and positioning."
    },
    {
        number: "02",
        title: "Core Idea",
        description: "Strength and originality of the core brand idea."
    },
    {
        number: "03",
        title: "Visual Design",
        description: "Quality of logo, colors, and typography."
    },
    {
        number: "04",
        title: "Consistency",
        description: "Consistency across all brand visuals and applications."
    },
    {
        number: "05",
        title: "Craft & Polish",
        description: "Craft and polish of the final designs."
    },
    {
        number: "06",
        title: "Real-World Usage",
        description: "Effectiveness of mockups and real-world brand usage."
    },
    {
        number: "07",
        title: "Design Process",
        description: "How clearly the design process and thinking are shown."
    },
    {
        number: "08",
        title: "Brand Story",
        description: "How well the brand story is communicated."
    },
    {
        number: "09",
        title: "Presentation",
        description: "Confidence and clarity of the final presentation."
    }
]

export default function FeatureCards() {
    const containerRef = useRef<HTMLDivElement>(null)
    const sliderRef = useRef<HTMLDivElement>(null)

    useEffect(() => {
        gsap.registerPlugin(ScrollTrigger)

        const ctx = gsap.context(() => {
            const container = containerRef.current
            const slider = sliderRef.current

            if (!container || !slider) return

            const cards = Array.from(slider.children) as HTMLElement[]
            if (cards.length === 0) return

            // Function to calculate movement limits (same as HorizontalSlides)
            const getScrollValues = () => {
                const containerCenter = container.clientWidth / 2
                const firstCard = cards[0]
                const lastCard = cards[cards.length - 1]

                // Calculate center points of first and last cards relative to the slider
                const firstCardCenter = firstCard.offsetLeft + firstCard.offsetWidth / 2
                const lastCardCenter = lastCard.offsetLeft + lastCard.offsetWidth / 2

                // Calculate the X offsets needed to center these cards
                const startX = containerCenter - firstCardCenter
                const endX = containerCenter - lastCardCenter

                // Total distance to move
                const totalMove = Math.abs(endX - startX)

                return { startX, endX, totalMove }
            }

            // How much extra spacing to wait after scroll finishes (in pixels)
            const pauseAmount = window.innerHeight * 0.75

            const tl = gsap.timeline({
                scrollTrigger: {
                    trigger: container,
                    start: 'top top',
                    // The total scroll distance is movement + pause
                    end: () => {
                        const { totalMove } = getScrollValues()
                        return `+=${totalMove + pauseAmount}`
                    },
                    scrub: 1,
                    pin: true,
                    anticipatePin: 1,
                    invalidateOnRefresh: true,
                },
            })

            // Use fromTo to explicitly control start and end positions
            tl.fromTo(slider,
                {
                    x: () => getScrollValues().startX
                },
                {
                    x: () => getScrollValues().endX,
                    ease: 'none',
                    duration: 1,
                }
            )

            // Add a pause of proportional duration
            tl.to({}, {
                duration: () => {
                    const { totalMove } = getScrollValues()
                    return pauseAmount / totalMove
                }
            })
        }, containerRef)

        return () => ctx.revert()
    }, [])

    return (
        <div className="feature-cards" ref={containerRef}>
            <div className="feature-cards-slider" ref={sliderRef}>
                {features.map((feature, i) => (
                    <div key={feature.number} className="feature-card card" style={{ '--index': i } as React.CSSProperties}>
                        <div className="feature-number">{feature.number}</div>
                        <h3 className="feature-title">{feature.title}</h3>
                        <p className="feature-description">{feature.description}</p>
                    </div>
                ))}
            </div>
        </div>
    )
}

// BuildBrand-main/src/lib/components/FeatureCards/FeatureCards.svelte
<script lang="ts">
	import { onMount, type ComponentType, createEventDispatcher } from 'svelte';
	import cn from 'clsx';

	import { useRect } from '$lib/lifecycle-functions/useRect';
	import { useWindowSize } from '$lib/lifecycle-functions/useWindowSize';
	import { useScroll } from '$lib/lifecycle-functions/useScroll';
	import { clamp, mapRange } from '$lib/utils/maths';

	import Card from '../Card.svelte';

	const cards = [
		{ text: 'Clarity of the brand’s purpose, audience, and positioning.' },
		{ text: 'Strength and originality of the core brand idea.' },
		{ text: 'Quality of logo, colors, and typography.' },
		{ text: 'Consistency across all brand visuals and applications.' },
		{
			text: 'Craft and polish of the final designs.'
		},
		{ text: 'Effectiveness of mockups and real-world brand usage.' },
		{ text: 'How clearly the design process and thinking are shown.' },
		{ text: 'How well the brand story is communicated.' },
		{
			text: 'Confidence and clarity of the final presentation.'
		}
	];

	let AppearTitle: ComponentType;
	let containerRef: HTMLDivElement;
	let elementRef: HTMLDivElement;
	let current: number = -1;

	const emit = createEventDispatcher();

	const [windowSize] = useWindowSize();
	const [setRef, rect] = useRect();

	onMount(async () => {
		AppearTitle = (await import('../AppearTitle.svelte')).default;

		setRef(containerRef);

		emit('mounted');
	});

	useScroll(({ scroll }) => {
		if (!elementRef) return;

		const start = $rect.top - $windowSize.height * 2;
		const end = $rect.top + $rect.height - $windowSize.height;

		const progress = clamp(0, mapRange(start, end, scroll, 0, 1), 1);

		elementRef.style.setProperty(
			'--progress',
			String(clamp(0, mapRange($rect.top, end, scroll, 0, 1), 1))
		);

		current = Math.floor(progress * 10);
	});
</script>

<div bind:this={containerRef} class="features">
	<div class="layout-block-inner sticky">
		<aside class="title">
			<p class="h3">
				<svelte:component this={AppearTitle}
					>How We'll Judge
					<br />
					<span class="grey">Your Work</span></svelte:component
				>
			</p>
		</aside>
		<div bind:this={elementRef}>
			{#each cards as card, index (index)}
				<div class={cn('card', index <= current - 1 && 'current')} style={`--i: ${index}`}>
					<Card background="rgba(239, 239, 239, 0.8)" number={index + 1} text={card.text} />
				</div>
			{/each}
		</div>
	</div>
</div>

<style lang="scss">
	@use '../../styles/functions' as *;

	.features {
		height: 1000vh;

		@include desktop {
			height: 1600vh;
			min-height: desktop-vw(1310px);
		}

		.card {
			--d: 100vh;

			position: absolute;
			will-change: transform;
			transition-duration: 1.2s;
			transition-property: opacity, transform;
			transition-timing-function: var(--ease-out-expo);

			@include mobile {
				@for $i from 0 through 8 {
					&:nth-child(#{$i + 1}) {
						top: calc(
							(((100 * var(--vh, 1vh)) - #{mobile-vw(440px)} - (var(--layout-margin))) / 8) * $i
						);
					}
				}
			}

			@include desktop {
				@for $i from 0 through 8 {
					&:nth-child(#{$i + 1}) {
						top: calc(((var(--d) - #{desktop-vw(440px)} - (2 * var(--layout-margin))) / 8) * $i);
						left: calc(((100vw - #{desktop-vw(440px)} - (2 * var(--layout-margin))) / 8) * $i);
					}
				}
			}

			&:not(.current) {
				transform: translate3d(100%, 100%, 0);
				opacity: 0;
			}
		}

		.title {
			text-align: start;
			padding-bottom: var(--layout-margin);

			@include desktop {
				padding: 0;
				position: absolute;
				left: var(--layout-margin);
				bottom: var(--layout-margin);
			}

			.h3 {
				color: #ffffff;
				font-size: mobile-vw(28px);

				@include desktop {
					font-size: desktop-vw(34px);
				}

				.grey {
					color: #ffffff;
				}
			}
		}
	}

	.sticky {
		overflow: hidden;
		position: sticky;
		top: 0;
		height: 100vh;
		padding: var(--layout-margin);

		@include desktop {
		}

		> * {
			position: relative;
		}
	}
</style>
